services:
  db:
    build:
      ./database/
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      ./src/
    ports:
      - 80:5000
    depends_on:
      - db
volumes:
  db_data: